# Generated by Django 5.2.17 on 2026-09-28 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('location', models.CharField(max_length=160)),
                ('facility_type', models.CharField(max_length=40)),
                ('contracted_limit_kw', models.FloatField()),
                ('warning_ratio', models.FloatField(default=0.8)),
                ('critical_ratio', models.FloatField(default=0.95)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, max_digits=8)),
                ('demand_rate_per_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('penalty_per_kw', models.DecimalField(decimal_places=2, max_digits=8)),
                ('solar_capacity_kw', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('load_kw', models.FloatField()),
                ('solar_kw', models.FloatField()),
                ('grid_kw', models.FloatField()),
                ('load_kwh', models.FloatField()),
                ('solar_kwh', models.FloatField()),
                ('grid_kwh', models.FloatField()),
                ('export_kwh', models.FloatField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='energy.facility')),
            ],
            options={
                'ordering': ['recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'recorded_at'), name='unique_reading_at')],
            },
        ),
    ]
